remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true

github:
  is_project_page: false

title: Programaci√≥n
description: Apuntes de Desarrollo Web Entorno Servidor del CFGS de Desarrollo de Aplicaciones Web.

show_downloads: false
